### ISSUE TITLE
Ready vote to start the match

### ISSUE THREAD

**Issue by JosVroegindeweij** [TheSuperNooby/PyPlanet#13]
After the admin has selected the players, have the players type in a command to signal they are ready. Once all players have done this, start the banning phase.

Command might be /ready (alias /r) or something more specific to this app, like /match ready (/brawl ready)

**Comment by TheSuperNoob** [comment]
Good idea! We can also take in use some GUI here too. Like when you do a callvote, theres a small bar near the middle of the screen that opens up and you can click green Yes [F5] or red No [F6] as well as having the commands for it

**Comment by JosVroegindeweij** [comment]
Yes! implementing it with the regular voting system might even be better, because there doesn't need to be a specific command, just a /y which already exists. I don't know if that's possible though. Personally I like the chat voting system better than the ingame, but that's personal preference. Also, I don't know how easy it would be to combine the 2
